### ISSUE TITLE
Use metrics-java instead of MetricPoint

### ISSUE THREAD

**Issue by keshavpeswani** [ExpediaDotCom/haystack-trends#155]
Migrate Haystack Trends to use [metrics-java](https://github.com/ExpediaDotCom/metrics-java) instead of internal MetricPoint.

**Comment by ayansen** [comment]
metrics-java is a library which contains the standard definition for time-series metrics at Expedia. We intend to use the same library across open-source projects in Expedia such as Adaptive Alerting and Haystack.
